<?php

Class COtrsClient {

    var $client;
    var $user = "soap_user";
    var $pass = "NSh1gl";
    var $clientUrl = "http://otrs.cyberphoto.se/znuny/rpc.pl";
    /**
     * Creates new instance of otrs client. 
     * All parameters are optional. If dismissed default values are used
     * @param type $url - optional
     * @param type $user
     * @param type $pass
     */
    function __construct($url, $user, $pass) {
        if ($url != "" )
            $this->clientUrl = $url;
        if ($user != "" )
            $this->user = $user;
        if ($pass != "" )
            $this->pass = $pass;
        
        $this->setClient();
    }

    public function setClient() {
        $this->client = new SoapClient(null, array('location' =>
                    $this->clientUrl,
                    'uri' => "Core",
                    'trace' => 1,
                    'login' => $this->user,
                    'password' => $this->pass,
                    'style' => SOAP_RPC,
                    'use' => SOAP_ENCODED));
    }

    /**
     * 
     * @param type $queue
     * @param type $from
     * @param type $customerEmail
     * @param type $title
     * @param type $message - plain text, html can not be used
     */
    public function addticket($queue, $from, $customerEmail, $title, $message, $utf8_encoded = true) {
        
        // Data is already UTF-8, no conversion needed
        
        # creating a ticket number
        $ticketnr = $this->client->
                __soapCall("Dispatch", array($this->user, $this->pass, "TicketObject", "TicketCreateNumber"));
        
        #php changes long numbers to 123E+10 notation to prevent this screwing up our ticketnumbers we convert notation
        #it into normal plain numbers. but only if not string, because sometimes you have a string addition like XY123 on your
        #ticket numbers
        if (!is_string($ticketnr))
            $ticketnr = number_format($ticketnr, 0, '.', '');

        # create the new ticket
        //$title = "some test title";
        //$queue = "IT-support";
        $customerid = $customerEmail;
        //$customeruser = "John Doe";
        $userid = 1;   # your OTRS-Userid, varies of course in every installation
        $UserID = 1;
        $ticketid = $this->client->
                __soapCall("Dispatch", array($this->user, $this->pass, "TicketObject", "TicketCreate",
            "TN", $ticketnr,
            "Title", "[ Ticket#: " . $ticketnr . " ] " . $title,
            //"Title", "" . $title .  "                 [ Ticket#: " . $ticketnr . " ] ",
            "Queue", $queue,
            "Lock", "unlock",
            "PriorityID", 3,
            //"Priority", '3 normal',
            //"State", "closed successful",
            "State", "new",
            "CustomerId", $customerid,
            "CustomerUser", $customerEmail,
            "OwnerID", $userid,
            "UserID", $userid
                ));

        #create the new e-mail message, which is send out and attached to the ticket automatically

        $from = $from;
        $to = $customerEmail;
        //$message = "pay your bills";
        $subject = $title;

        $articleid = $this->client->
                __soapCall("Dispatch", array($this->user, $this->pass, "TicketObject", "ArticleSend",
            "TicketID", $ticketid,
            "ArticleType", "email-external",
            "SenderType", "system",
            "From", $from,
            "To", $to,
            "ReplyTo", "",
            //"Subject", "[ Ticket#: " . $ticketnr . " ] " . $subject,
            "Subject", "" . $subject . " [Ticket#: " . $ticketnr . " ] " ,
            "Body", $message,            
            //"ContentType", "text/html charset=utf-8",
            //"Content-Type", "text/html; charset=ISO-8859-1",
                    //text/html; charset="iso-8859-15"
            "Charset", "utf-8",
            "MimeType", "text/html",
            "ContentType"      , "text/html;charset=utf-8",
            "Content-Transfer-Encoding", "quoted-printable", 
            "HistoryType", "EmailCustomer",
            "HistoryComment", "generated by OTRSInterface-Class",
            "UserID", $userid,
            "NoAgentNotify", 0,
            "MimeType", "text/plain",
            "Loop", 0
                ));
        return $ticketnr;
    }
    public function addTicketTest($title, $from) {
        try {
            $ticketnumber = $this->client->__soapCall("Dispatch", array($this->user, $this->pass, "TicketObject", "TicketCreateNumber"));
            echo "TicketNumber: " . $ticketnumber . "<br>";

            $ticket = $this->client->__soapCall("Dispatch", array($this->user, $this->pass, "TicketObject", "TicketCreate",
                "TN", $ticketnumber,
                "Title", 'Some Ticket Title',
                "Queue", 'IT-support',
                "Lock", 'unlock',
                "Priority", '3 normal',
                "State", 'new',
                "Type", 'default',
                "Service", '',
                "SLA", '',
                "CustomerID", '',
                "CustomerUser", $from,
                "OwnerID", 1,
                "ResponsibleID", 1,
                "UserID", 1
                    ));

            $article = $this->client->__soapCall("Dispatch", array($this->user, $this->pass, "TicketObject", "ArticleCreate",
                "TicketID", $ticket,
                "ArticleType", 'email-external',
                "SenderType", 'customer',
                "From", 'customer@example.com',
                "To", 'otrs@localhost',
                "Cc", '',
                "ReplyTo", '',
                "Subject", 'some subject',
                "Body", 'the message text',
                "MessageID", '',
                "ContentType", 'text/html; charset=utf-8',
                "HistoryType", 'OwnerUpdate',
                "HistoryComment", 'Some free text!',
                "UserID", 1,
                "NoAgentNotify", 1,
                "AutoResponseType", '',
                "ForceNotificationToUserID", 1
                    ));

            $accountid = $this->client->__soapCall("Dispatch", array($this->user, $this->pass, "TicketObject", "TicketFreeTextSet",
                "Counter", 1,
                "Key", 'Product',
                "Value", 'Notebook',
                "TicketID", $ticket,
                "UserID", 1
                    ));
        } catch (SoapFault $fault) {
            echo "REQUEST:\n" . $this->client->__getLastRequest() . "\n";
            echo "RESPONSE:\n" . $this->client->__getLastResponse() . "\n";
            echo "</pre>";
            exit;
        }
        echo "REQUEST:\n" . $this->client->__getLastRequest() . "\n";
        echo "RESPONSE:\n" . $this->client->__getLastResponse() . "\n\n";
        echo "Response Array:<br>";
        var_dump($ticket);
        var_dump($article);
        var_dump($accountid);
        echo "</pre>";
    }

}

?>