/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DateTest */

#ifndef _Included_DateTest
#define _Included_DateTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
